FROM archlinux:latest as archlinux-nodeps

RUN pacman -Suy --noconfirm \
    cmake \
    clang \
    ninja \
    mold \
    libc++

FROM archlinux-base AS archlinux-withdeps

RUN pacman -Suy --noconfirm \
    sdl3
